version: "2.4"

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432
    volumes:
      - ./pg:/docker-entrypoint-initdb.d/
      - ./pg-data:/bar/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  api:
    build: ./api
    init: true
    command: npm run watch
    volumes:
      - ./api/src:/server/src
      - ./api/dist:/server/dist
    ports:
      - "3000:3000"
      - "5858:5858"
    environment:
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=password
      - PORT=3001
    links:
      - db
  # ui:
  #   init: true
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './ui:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - '6969:3000'
  #     - '6970:3001'
  #   environment:
  #     - NODE_ENV=development
  #     - CLIENT_PUBLIC_PATH=http://localhost:6970/
  #     - CHOKIDAR_USEPOLLING=true
  #     - API_URL=api
  #     - VERBOSE=true
