CREATE DATABASE spottyfi;
\c spottyfi;
CREATE ROLE spottyfi;
GRANT ALL ON DATABASE spottyfi TO spottyfi;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO spottyfi;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO spottyfi;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
